# ABOUTME: GitHub Actions workflow for continuous integration
# Runs on pushes to master branch to ensure code quality

name: CI

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting and formatting checks
        run: |
          npm run lint:check
          npm run format:check
      
      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage reports
        if: always()  # Upload coverage even if tests fail
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
        continue-on-error: true

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Test Expo build
        run: npx expo export --platform web

  expo-publish:
    name: Publish to Expo (Preview)
    runs-on: ubuntu-latest
    if: false  # Enable when ready to publish previews
    needs: [test, build-test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish to Expo
        run: eas update --branch preview --message "${{ github.event.head_commit.message }}"