name: E2E Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  EXPO_NO_DOTENV: 1
  EXPO_USE_METRO_WORKSPACE_ROOT: 1

jobs:
  e2e-ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Setup iOS Simulator
        run: |
          # List available simulators
          xcrun simctl list devices available
          # Create and boot iPhone 15 Pro simulator
          DEVICE_ID=$(xcrun simctl create "iPhone 15 Pro" "com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro" "com.apple.CoreSimulator.SimRuntime.iOS-17-2")
          xcrun simctl boot "$DEVICE_ID"
          # Wait for simulator to boot
          xcrun simctl bootstatus "$DEVICE_ID"

      - name: Start Expo dev server
        run: |
          npx expo start &
          sleep 30  # Wait for server to start
        env:
          EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0

      - name: Create screenshots directory
        run: mkdir -p tests/e2e/screenshots

      - name: Run E2E tests
        run: |
          # Run basic test first
          npm run test:e2e:basic || true
          # Run full test suite with retry logic
          npm run test:e2e:ios || npm run test:e2e:ios || true
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 120000
          MAESTRO_FLOW_TIMEOUT: 300000

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots-ios
          path: tests/e2e/screenshots/

  e2e-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          avd-name: test
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            # Wait for emulator to be ready
            adb wait-for-device
            adb shell input keyevent 82
            # Start Expo dev server
            npx expo start --android &
            sleep 45  # Wait for server to start
            # Create screenshots directory
            mkdir -p tests/e2e/screenshots
            # Run basic test first
            npm run test:e2e:basic || true
            # Run E2E tests with retry logic
            npm run test:e2e:android || npm run test:e2e:android || true

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots-android
          path: tests/e2e/screenshots/